const int_packages = [
    {
        destination: 'Bali',
        duration: '4N/5D',
        persons: 2,
        description: 'Discover amazing places of the world with us',
        image: '../img/Bali/bali2.jpg',
        rating: 4.5,
        reviews: 250,
        price: 350,
        path:'/singleCard/Bali.html',
    },
    {
        destination: 'Dubai ',
        duration: '4N/5D',
        persons: 2,
        description: 'Explore beautiful beaches and cultural landmarks',
        image: '../img/Dubai/uWf0H5vbDu.jpg',
        rating: 4.5,
        reviews: 300,
        path:'/singleCard/dubai.html',

    },
    // {
    //     destination: 'Atlantis Palm ',
    //     duration: '5N/6D',
    //     persons: 2,
    //     description: 'Adventure and relaxation, all in one package',
    //     image: 'https://imgcy.trivago.com/c_fill,d_dummy.jpeg,e_sharpen:60,f_auto,h_534,q_40,w_800/hotelier-images/f9/d6/8e208e994323c165e1828fb077d3b64cc01e4cd1a43f64106dc36bbf36af.jpeg',
    //     rating: 4.9,
    //     reviews: 150,
    //     price: 500,
    //     path:'/singleCard/Atlantis.html',
    // },
    {
        destination: 'Maldives',
        duration: '4N/5D',
        persons: 2,
        description: 'Escape to a tropical paradise with crystal-clear waters and pristine beaches',
        image: '../img/Maldives/maldives.jpg',
        rating: 4.9,
        reviews: 150,
        price: 500,
        path:'/singleCard/Maldives.html',
    },
    {
        destination: 'Seychells',
        duration: '5N/6D',
        persons: 2,
        description: 'Experience the breathtaking beauty of Seychelles, with its stunning beaches and crystal-clear waters',
        image: '../img/Seychelles/W9xb36jYsr.jpg',
        rating: 5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Seychells.html',
    },
    {
        destination: 'Singapore',
        duration: '4N/5D',
        persons: 2,
        description: 'Experience the vibrant culture and modern attractions of Singapore',
        image: '../img/Singapore/singapore-city-skyline-P238A3R.jpg',
        rating: 5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Singapore.html',
    },
   
    {
        destination: 'Sri Lanka',
        duration: '3N/4D',
        persons: 2,
        description: 'Experience the rich history, culture, and natural beauty of Sri Lanka',
        image: '../img/SriLanka/traveling-by-train-in-sri-lanka-RAL9NF2(1).jpg',
        rating: 4.8,
        reviews: 150,
        price: 500,
        path:'/singleCard/SriLanka.html',
    },
   
    {
        destination: 'Thailand',
        duration: '4N',
        persons: 2,
        description: 'Discover the bustling cities, stunning beaches, and rich culture of Thailand',
        image: '../img/Thailand/PEH8Hp9jBw.jpg',
        rating: 4,
        reviews: 150,
        price: 500,
        path:'/singleCard/Thailand.html',
    },
   
    // {
    //     destination: 'Malaysia',
    //     duration: '4N',
    //     persons: 2,
    //     description: 'Explore the vibrant culture, stunning beaches, and rich history of Malaysia with a mix of island and city life',
    //     image: '../img/Malaysia/Nh11MmuiAT.jpg',
    //     rating: 5,
    //     reviews: 150,
    //     price: 500,
    //     path:'/singleCard/Malaysia.html',
    // },
    // {
    //     destination: 'Kuala Lumpur',
    //     duration: '2N',
    //     persons: 2,
    //     description: 'Experience the vibrant culture, stunning Petronas Twin Towers, and rich history of Kuala Lumpur, a city that seamlessly blends tradition and modernity',
    //     image: 'https://www.new7wonders.com/app/uploads/sites/5/2016/09/Malaysia-Kuala-Lumpur.jpg',
    //     rating: 5,
    //     reviews: 150,
    //     price: 500,
    //     path:'contact.html',
    // },
    {
        destination: 'Bishkek',
        duration: '4N/5D',
        persons: 2,
        description: 'Explore the vibrant culture, stunning landscapes, and rich history of Bishkek, a city that seamlessly blends tradition and modernity',
        image: '../img/Bishkek/bhishkek.jpg',
        rating: 4.8,
        reviews: 150,
        price: 500,
        path:'/singleCard/Bishkek.html',
    },
    {
        destination: 'Hongkong & Macau',
        duration: '4N/5D',
        persons: 2,
        description: 'Experience the vibrant culture, stunning skyline, and rich history of Hong Kong and Macau, with a mix of city and island life',
        image: '../img/Hongkong&Macau/hOJHWVbRYj.jpg',
        rating: 4.1,
        reviews: 150,
        price: 500,
        path:'/singleCard/Hongkong.html',
    },
    {
        destination: 'Bhutan',
        duration: '5N/6D',
        persons: 2,
        description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas',
        image: '../img/Bhutan/dk7nQexUmG.jpg',
        rating: 3.5,
        reviews: 150,
        price: 500,
        path:'/singleCard/bhutan.html',
    },
    {
        destination: 'Nepal',
        duration: '5N/6D',
        persons: 2,
        description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
        image: '../img/Nepal/nepal.jpg',
        rating: 3.2,
        reviews: 150,
        price: 500,
        path:'/singleCard/Nepal.html',
    },
   

    // Add more packages as needed
];