const packages = [
    {
        destination: 'Gujarat',
        duration: '3N/4D',
        persons: 2,
        description: 'Discover amazing places of the world with us',
        image: '../img/Gujrat/6U8MVimOrt.jpg',
        rating: 4.5,
        reviews: 250,
        price: 350,
        path:'/singleCard/gujrat.html',
    },
    {
        destination: 'Goa ',
        duration: '4N/5D',
        persons: 2,
        description: 'Explore beautiful beaches and cultural landmarks',
        image: '../img/Goa/wkB2xMHpZb.jpg',
        rating: 4.5,
        reviews: 300,
        path:'/singleCard/goa.html',

    },
    {
        destination: 'Andaman & Nicobar',
        duration: '4N/5D',
        persons: 2,
        description: 'Adventure and relaxation, all in one package',
        image: '../img/Andman/andaman2.jpg',
        rating: 4.9,
        reviews: 150,
        price: 500,
        path:'/singleCard/andman.html',
    },
   
    {
        destination: 'Himachal Pradesh',
        duration: '3N',
        persons: 2,
        description: '3 Nights Honeymoon Volvo Package',
        image: '../img/Himachal/himachal.jpg',
        rating: 5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Himachal.html',
    },
    {
        destination: 'Hyderabad',
        duration: '2N/3D',
        persons: 2,
        description: 'Experience the vibrant culture and modern attractions of Singapore',
        image: '../img/Hyderabad/hydrabad.jpg',
        rating: 5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Hyderabad.html',
    },
 
    {
        destination: 'Karnataka',
        duration: '3N/4D',
        persons: 2,
        description: 'Experience the rich history, culture, and natural beauty of Sri Lanka',
        image: '../img/Karnataka/karnataka2.jpg',
        rating: 4.8,
        reviews: 150,
        price: 500,
        path:'/singleCard/Karnataka.html',
    },
   
    {
        destination: 'Kashmir',
        duration: '4N/5D',
        persons: 2,
        description: 'Discover the bustling cities, stunning beaches, and rich culture of Thailand',
        image: '../img/Kashmir/',
        rating: 4,
        reviews: 150,
        price: 500,
        path:'/singleCard/Kashmir.html',
    },
   
    {
        destination: 'Kerala',
        duration: '4N',
        persons: 2,
        description: 'Explore the vibrant culture, stunning beaches, and rich history of Malaysia with a mix of island and city life',
        image: '../img/Kerala/kerala2.jpg',
        rating: 5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Kerala.html',
    },
    {
        destination: 'Ladakh',
        duration: '5N/6D',
        persons: 2,
        description: 'Experience the vibrant culture, stunning Petronas Twin Towers, and rich history of Kuala Lumpur, a city that seamlessly blends tradition and modernity',
        image: '../img/Ladakh/ladakh.jpg',
        rating: 5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Ladakh.html',
    },
    // {
    //     destination: 'Darjeeling + Gangtok ',
    //     duration: '4N',
    //     persons: 2,
    //     description: 'Explore the vibrant culture, stunning landscapes, and rich history of Bishkek, a city that seamlessly blends tradition and modernity',
    //     image: 'https://www.indiantempletour.com/wp-content/uploads/2022/08/Gangtok-Darjeeling-Tour-Package.jpg',
    //     rating: 4.8,
    //     reviews: 150,
    //     price: 500,
    //     path:'/singleCard/Darjeeling.html',
    // },
    {
        destination: 'Odisha',
        duration: '3N',
        persons: 2,
        description: 'Experience the vibrant culture, stunning skyline, and rich history of Hong Kong and Macau, with a mix of city and island life',
        image: '../img/orrisa/orrisa.jpg',
        rating: 4.1,
        reviews: 150,
        price: 500,
        path:'/singleCard/Odisha.html',
    },
    {
        destination: 'Rajasthan',
        duration: '5N/6D',
        persons: 2,
        description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas',
        image: '../img/Rajasthan/raj.jpg',
    
        rating: 3.5,
        reviews: 150,
        price: 500,
        path:'/singleCard/Rajasthan.html',
    },
    {
        destination: 'Uttarakhand',
        duration: '4N/5D',
        persons: 2,
        description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
        image: '../img/Uttarakhand/nI9Az31yPj.jpg',
        rating: 3.2,
        reviews: 150,
        price: 500,
        path:'/singleCard/Uttarakhand.html',
    },
    {
        destination: 'Maharashtra',
        duration: '2N/3D',
        persons: 2,
        description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
        image: '../img/maharashtra.jpg',
        rating: 3.2,
        reviews: 150,
        price: 500,
        path:'/singleCard/Maharashtra.html',
    },
    // {
    //     destination: 'Mahabaleshwar',
    //     duration: '2N/3D',
    //     persons: 2,
    //     description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
    //     image: 'https://www.treksandtrails.org/system/images/000/534/553/5185670995fdf476a4a5865950bda147/x600gt/Mahabaleshwar-Sunset-1.jpg?1707391182',
    //     rating: 3.2,
    //     reviews: 150,
    //     price: 500,
    //     path:'/singleCard/mahabaleshwar.html',
    // },
    // {
    //     destination: 'Mumbai',
    //     duration: '2N/3D',
    //     persons: 2,
    //     description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
    //     image: 'https://i.ytimg.com/vi/73ag7pBlZec/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCCzqm9Nb-VNnmNcNPzwoAQaZQjIw',
    //     rating: 3.2,
    //     reviews: 150,
    //     price: 500,
    //     path:'/singleCard/Mumbai.html',
    // },
    // {
    //     destination: 'Kokan',
    //     duration: '4N/5D',
    //     persons: 2,
    //     description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
    //     image: '../img/konkan/CwsRnrgaBL.jpg',
    //     rating: 3.2,
    //     reviews: 150,
    //     price: 500,
    //     path:'/singleCard/kokan.html',
    // },
    {
        destination: 'Uttar Pradesh Package ',
        duration: '2N/3D',
        persons: 2,
        description: 'Experience the unique culture, breathtaking landscapes, and serene beauty of Bhutan, a hidden gem in the Himalayas, with its stunning monasteries, pristine valleys, and majestic mountains',
        image: '../img/Uttarpradesh/up.jpg',
        rating: 3.2,
        reviews: 150,
        price: 500,
        path:'/singleCard/agra-mathura.html',
    },
   

    // Add more packages as needed
];